REST_ENDPOINT: http://fcrepolocal/fcrepo/rest/pcdm
FEDORA_USER: fedoraAdmin
FEDORA_PASSWORD: secret3

PREDICATES:
    dcterms:title
    dcterms:issued
    dcterms:creator
    dc:identifier@type:lccn
    dc:isPartOf
    bibo:volume
    bibo:issue
    bibo:edition
    bibo:pageStart
    
    
