version: "3.7"
services:
  plastrond:
    image: docker.lib.umd.edu/plastrond
    configs:
      - source: plastrond
        target: /etc/plastrond.yml
      - source: archelon_id
        target: /etc/plastron/auth/archelon_id
        mode: 0400
    volumes:
      - plastrond-jobs:/var/opt/plastron/jobs
      - plastrond-messages:/var/opt/plastron/msg
    ports:
      - 5000:5000
configs:
  plastrond:
    file: docker-plastron.yml
  archelon_id:
    # Private key for archelon SFTP
    # The corresponding public key should be added to Archelon
    file: archelon_id
volumes:
  plastrond-jobs:
  plastrond-messages:
networks:
  default:
    external: true
    name: umd-fcrepo_default
