version: "3.7"
services:
  plastrond:
    image: docker.lib.umd.edu/plastrond
    configs:
      - source: plastrond
        target: /etc/plastrond.yml
    volumes:
      - plastrond:/var/opt/plastron
configs:
  plastrond:
    file: docker-plastron.yml
volumes:
  plastrond:
networks:
  default:
    external: true
    name: umd-fcrepo_default
