version: "3.7"
services:
  http:
    image: docker.lib.umd.edu/plastrond-http
    configs:
      - source: plastron-config
        target: /etc/plastron-config.yml
    volumes:
      - plastrond-jobs:/var/opt/plastron/jobs
    environment:
      - JOBS_DIR=/var/opt/plastron/jobs
    ports:
      - "5000:5000"
volumes:
  plastrond-jobs:
  plastrond-messages:
configs:
  plastron-config:
    file: ../docker-plastron.yml
networks:
  default:
    external: true
    name: umd-fcrepo_default
