[project]
name = "plastron-rdf"
version = "4.2.0-rc1"
requires-python = ">= 3.8"
dependencies = [
    "rdflib",
]

[project.optional-dependencies]
test = [
    "freezegun",
    "pytest",
    "pytest-cov",
]
