[project]
name = "plastron-client"
version = "4.2.0-dev2"
requires-python = ">= 3.8"
dependencies = [
    "rdflib",
    "requests",
    "requests-jwtauth",
    "urlobject",
]

[project.optional-dependencies]
test = [
    "freezegun",
    "pytest",
    "pytest-cov",
]
