HANDLER:         correspondence
COLLECTION:      http://localhost:8080/rest/pcdm/my-collection-uri
LOG_CONFIG:      /absolute/path/to/log/config.yml
LOG_DIR:         /absolute/path/to/log/dir
ROOT:  		       /absolute/path/to/batch/directory
MAPFILE:         mapfile.csv   # relative to LOG_DIR
BATCH_INDEX:     index.csv     # relative to ROOT / will write if not found
METADATA_FILE:   metadata.ttl  # relative to ROOT
METADATA_PATH:   metadata/     # relative to ROOT
DATA_PATH:       data/         # relative to ROOT
INCLUDE_PATTERN: |  
    ^                        # beginning of string
    (?P<proj>litmss)-        # project code
    (?P<ser_no>\d{6})        # six-digit serial number
    (?:-?                    # optional hyphen (not captured)
      (?P<seq_no>\d{4})?)    # optional four-digit seq number
    (?:\.                    # literal dot (not captured)
      (?P<ext>\S+))          # file extension
    $                        # end of string
