[project]
name = "plastron-repo"
version = "4.0.0-dev"
requires-python = ">= 3.8"
dependencies = [
    "bagit",
    "paramiko",
    "PyYAML",
    "rdflib",
    "requests",
    "URLObject",
]

[project.optional-dependencies]
test = [
    "freezegun",
    "pytest",
    "pytest-cov",
]
